### ISSUE TITLE
Enable mailhide / mailhide option page?

### ISSUE THREAD

**Issue by strarsis** [blaenk/wp-recaptcha#70]
I find code for mailhide in this repository, also for an option page - 
but I cannot find it in WordPress admin backend.

**Comment by blaenk** [comment]
This plugin was handed over to Google long ago. This repository is an archive of a very old version of the plugin. I no longer work on it.

**Comment by strarsis** [comment]
@blaenk: A link in the README page to where the official repository is located would be nice. I wasn't able to find it immediately.

**Comment by blaenk** [comment]
I agree, though I have no idea what Google have done with it. It seems that the SVN repo [remains available](https://plugins.svn.wordpress.org/wp-recaptcha/trunk/). Sorry for the inconvenience.

**Comment by strarsis** [comment]
@blaenk: No problem. The plugin is nice though (even this old one). :)
